<?php

namespace App\Forms;

use SilverStripe\Control\RequestHandler;
use SilverStripe\Forms\CheckboxSetField;
use SilverStripe\Forms\DropdownField;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\Form;
use SilverStripe\Forms\FormAction;
use TheWebmen\Articles\Validators\ArticleFilterFormValidator;

class ArticleFilterForm extends Form
{
    public function __construct(RequestHandler $controller = null, $name = self::DEFAULT_NAME)
    {
        $fields = new FieldList(
            CheckboxSetField::create(
                'thema',
                'Thema\'s',
                $controller->getThemes()->map('URLSegment')->toArray()
            ),
            DropdownField::create(
                'type',
                'Type',
                $controller->getTypes()->map('Slug', 'Title')->toArray()
            )->setHasEmptyDefault(true)->setEmptyString('Choose a type')
        );

        $actions = new FieldList(
            FormAction::create('doArticleFilterForm', 'Filter')
                ->setName('')
        );

        parent::__construct($controller, '', $fields, $actions);

        $this->setFormMethod('GET');
        $this->disableSecurityToken();
        $this->loadDataFrom($controller->getRequest()->getVars());
    }

    public function getValidator()
    {
        return parent::getValidator(); // TODO: Change the autogenerated stub
    }
}
